stages:
  - build

services:
  - name: docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  script:
    - echo "Building all services..."
    - docker compose build 
    - docker images
  only:
    - project

