stages:
  - build

services:
  - name: docker:stable-dind
    alias: thedockerhost

variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - echo "Building all services..."
    - docker-compose build 
    - docker images
  only:
    - project
