stages:
  - build
  - pylint
  - test
  - deploy

services:
  - name: docker:20.10.9-dind
    alias: thedockerhost
  - name: nginx:latest
    alias: nginx

variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - echo "Beginning of build stage"
    - docker-compose up --build -d
    - docker images
    - echo "End of build stage"
  only:
    - project

pylint:
  stage: pylint
  image: python:3.12
  script:
    - apt-get update && apt-get install -y dnsutils
    - nslookup nginx
    - echo "Beginning of pylint stage"
    - pip install pylint requests docker flask
    - pylint --fail-under=8 ./tests/*.py
    - pylint --fail-under=8 ./service1/*.py
    - echo "End of pylint stage"
  only:
    - project

test:
  stage: test
  services:
    - docker:dind
    - name: nginx:latest
      alias: nginx
      ports:
        - "8197:8197"
  variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  image: python:3.12
  # image: docker:latest
  script:
    - echo "Beginning of test stage"
    - pip install requests
    - python3 -m unittest discover -s tests || exit 1
    # - docker run --network=test-network --name nginx -d 8197:8197 nginx:latest
    # - docker-compose run test || exit 1
  after_script:
    - docker-compose down
    - echo "End of test stage"
  only:
    - project

deploy:
  stage: deploy
  script:
    - echo "Beginning of deploy stage"
    - docker-compose up -d
    - docker-compose ps
    - echo "End of deploy stage"
  only:
    - project