stages:
  - build
  - test
  - deploy

services:
  - name: docker:20.10.9-dind
    alias: thedockerhost

variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - echo "Beginning of build stage"
    - docker-compose build 
    - docker images
    - echo "End of build stage"
  only:
    - project

test:
  stage: test
  script:
    - echo "Beginning of test stage"
    - docker-compose up --build test
    - docker-compose down
    - echo "End of test stage"
  only:
    - project

deploy:
  stage: deploy
  script:
    - echo "Beginning of deploy stage"
    - docker-compose up -d
    - docker-compose ps
    - echo "End of deploy stage"
  only:
    - project