stages:
  - build
  - test
  - deploy

services:
  - name: docker:20.10.9-dind
    alias: thedockerhost

variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - echo "Building all services..."
    - docker-compose build 
    - docker images
  only:
    - project

test:
  stage: test
  script:
    - echo "Running tests ..."
    - docker-compose up --build test
    - docker-compose down
  only:
    - project

deploy:
  stage: deploy
  script:
    - echo "Deploying services..."
    - docker-compose up -d
    - docker-compose ps
  only:
    - project
    - main