services:
  service1:
    build: ./service1
    expose:
      - "8199:8199"
    deploy:
      replicas: 3
    depends_on:
      - service2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  service2:
    build: ./service2
    ports:
      - "8200:8200"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    build: ./nginx
    ports:
      - "8198:8198"
      - "8197:8197"
    depends_on:
      - service1
      - service2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/index.html:/usr/share/nginx/index.html
      - ./nginx/index.js:/usr/share/nginx/index.js

  test:
    build: ./tests
    depends_on:
      - nginx
