services:
  service1:
    build: ./service1
    expose:
      - "8199:8199"
    deploy:
      replicas: 3
    depends_on:
      - service2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  service2:
    build: ./service2

  nginx:
    build: ./nginx
    ports:
      - "8198:8198"
    depends_on:
      - service1